[project]
name = "aix"
version = "0.1.0"
description = "AI Expense Tracker"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "python-dotenv>=1.1.0",
    "sqlmodel>=0.0.24",
]
